Repository getdokan/dokan-wpml, pull requests merged in 2025-02, with the labels that each got.

#95 update: Vendor store url additional endpoint translation added
  dokan-wpml.php
Labels: QA Approved, Dev Review Done, Upcoming Release

#91 fix: vendor vacation, biography `dokan-pro` support
  dokan-wpml.php
Labels: Needs Dev Review, QA Approved, Upcoming Release

#94 🚀 enhance: Dokan single store endpoint translation support
  dokan-wpml.php
Labels: QA Approved, Dev Review Done

#96 update: shipping method title translate support
  dokan-wpml.php
Labels: Needs Dev Review, QA Approved

#97 fix: product status count fix for vendor dashboard
  dokan-wpml.php
Labels: Needs Dev Review, QA Approved
